apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: v1.15.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    extraArgs:
    - "--dns01-recursive-nameservers=162.159.27.72:53,8.8.8.8:53"
    nodeSelector:
      lke.linode.com/pool-id: "125654"
    webhook:
      nodeSelector:
        lke.linode.com/pool-id: "125654"
    cainjector:
      nodeSelector:
        lke.linode.com/pool-id: "125654"