actions:
  1:
    action: delete_indices
    options:
      ignore_empty_list: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 2
  2:
    action: delete_indices
    options:
      ignore_empty_list: True
    filters:
    - filtertype: pattern
      kind: prefix
      value: wiki-52poke-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 7