apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: 52poke-wiki
  namespace: default
spec:
  maxReplicas: 8
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 52poke-wiki