apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- "deployment.yaml"
- "service.yaml"
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: 52poke-wiki-1-39
  files:
  - "LocalSettings.php=LocalSettings.php"