apiVersion: v1
data:
    password: ENC[AES256_GCM,data:F8nm1hHEVJi8VvP+glRQqLaCsbCA/CSW,iv:NdvjcfwzdFFuKYhypYYKmHPPL8mU/zAlulQEFIMC5Ic=,tag:QzMCdWWM3i40Muf0rm7k/g==,type:str]
    username: ENC[AES256_GCM,data:Yooe5g==,iv:zO8X61ErRl1f6ErWug3jqBejvgcsGkNlAMONMM5lA2o=,tag:pzHDTh1PxMBNWaC3bfcWbA==,type:str]
kind: Secret
metadata:
    name: mysql-www
    namespace: default
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zefy3yk8qkmr7zvk4fcc09ea9rt0a02kx28yygerx7usu780k9msuy6jth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUFZlczQ5eWdWYnlzV2V4
            NFJQTXVlYWJlSVpmMk9Lc2xWSzljS2pFODNNCm0vUVY5a1VkNXRRN2tsQUhrejMy
            ZmRSRndRcEQyZEZ5UEtJb0hIZ3J0dTgKLS0tIDBOcDRjNEVXVzFKYzZFTkZKVm9j
            aEk5RW0vNkJEQjUvNW9lUllSbzVLWmsKJIsKzsWX0eqVtYAs+UMoJsMUXguks3P+
            sJn8vBecOkTDlaG37W+AUmEt2Af4EDiPE8ihfrGeAxzM1gAhonBFDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T11:38:16Z"
    mac: ENC[AES256_GCM,data:96OtolJCK/lGuzhQuP79iYYPUSV3IbZRdW9X/JMQrEuSYoCuo2wKF4Ohs9uZZ/sCZ4EGNMzgZ0hk5t7uGgwbJ2eunKHqtBCVcb/0pEQMaZQwghxZ3gJ/cmkDVFiEJDEktfOKKQjLIlHPxEr7U+nsXyMSHXFOKKic+c1BglE+aqA=,iv:kAJofZRTTVc9LAVJ6DDnzJ+Ox6/hJadQA89bUKkgUkE=,tag:IPAInFDXccvfpSIF4g3RhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|accessKeyID|password)$
    version: 3.7.3
