apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: le-http-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: no-reply@52poke.net
    privateKeySecretRef:
      name: le-http-issuer
    solvers:
    - http01:
        ingress:
          class: nginx