apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: le-wildcard-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: no-reply@52poke.net
    privateKeySecretRef:
      name: le-wildcard-issuer
    solvers:
    - dns01:
        webhook:
          solverName: linode
          groupName: 52poke.com
