controller:
  config:
    log-format-escape-json: "true"
    log-format-upstream: '{"timestamp": "$time_iso8601", "remote_addr": "$remote_addr", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent"}'
    use-proxy-protocol: "true"
    block-user-agents: "~*ThinkBot*"
  
  nodeSelector:
    lke.linode.com/pool-id: "${pool_id}"
  
  replicaCount: 1

  service:
    externalIPs:
    - ${load_balancer_ip}
    type: NodePort
    nodePorts:
      http: "${http_port}"
      https: "${https_port}"