apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-postgres
  namespace: default
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
          - env:
            - name: POSTGRES_HOST
              value: postgres
            - name: RCLONE_CONFIG_BACKUP_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: b2-account-id
                  name: backblaze-b2
            - name: RCLONE_CONFIG_BACKUP_KEY
              valueFrom:
                secretKeyRef:
                  key: b2-account-key
                  name: backblaze-b2
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres
            - name: BACKUP_TARGET
              value: 52poke-backup/database
            image: mudkip/postgres-backup:latest
            imagePullPolicy: Always
            name: backup-postgres
          restartPolicy: OnFailure
  schedule: 30 19 * * *
  successfulJobsHistoryLimit: 1