auth:
  rootPassword: "${mongodb_password}"
persistence:
  storageClass: linode-block-storage-retain
  size: 20Gi
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 768Mi
nodeSelector:
  lke.linode.com/pool-id: "${pool_id}"