apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4LBdrOhDPriihOkgWVHNesjiQo10MTCI,iv:dRH+jAWVBOyVp3evi7iGH7l2ThgoxRAMU/yRuq+x/7g=,tag:oldH7MnqScE5q8g6nhHEoA==,type:str]
    username: ENC[AES256_GCM,data:wFzU4CheUWJoYGQA,iv:yGMjo5Xs7qqtzATWFAOoAFJ4zN2O+kgOCVrYSKkQ6bk=,tag:6txW8YjpM46UgWvRAU8K2Q==,type:str]
kind: Secret
metadata:
    name: postgres
    namespace: default
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zefy3yk8qkmr7zvk4fcc09ea9rt0a02kx28yygerx7usu780k9msuy6jth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ2lmWmNEcnRXcnAwTCtB
            eHFkTGM3Y2RGL1NPSldwbGxsM0J1QUxtM3g4CjJRdkdpS3RrZlhMQmRPbGkxVTRP
            SFYxYkJKN2RVR0RtYmJhd0ZhamZabDgKLS0tIHFpWlBYb3VqZ1lVZlhRNlh1K3Bi
            OEJ2c1FJUWd5elIzTi85MlBTOVowNmcKt71knVhexx+AXKIs8eohzW6cCo2lZ8xN
            084iEbGy/kbZ32Z+VTly+GcVJsVw1pAfVTF9TEBgMJXUGuIiktaORg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T11:39:15Z"
    mac: ENC[AES256_GCM,data:Z3Bp3zGEMbF+DnDFBkg/lriXpJpMMeJIvaoewZaEZAQ9LjUq6UcyVZQrWzg/9o98NE/csU/FOOKV+5xtKD+yt7IlYHHTA7va43Chs/kW+HnG0489O5vq52pShDoW3H0rgrGk+pRvvTur7Dqc5N/Ng8ZanyImWzr8b+/nwMIAuvA=,iv:n58Aw+5tNR6lMKnNXY8XLMC0jORubYUCaxfYnmV/wGs=,tag:0BBa+jgwg5xx6cyHOTn1QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|accessKeyID|password)$
    version: 3.7.3
