apiVersion: v1
data:
    accessKeyID: ENC[AES256_GCM,data:BCIrge0RFYNtprMEcBOowh/fn1+7nRT5RaFXUg==,iv:p+xKFEJufprTa7mvgzzJsqvHnFwvhuZtOoYvMJ+yogo=,tag:ZXugZ5hqGiIHNIB7t4LlHw==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:zLIaqMce0e/ZQ3SafwfikYqRb5VIaid276Ddho9BEQP0RBlqYWiJ4p7ZtULtQ8/nJD2Hi4gQi9o=,iv:tSXA8zi/KT7+eaXGEfv6Hr8FRQl9fLxit94B/RiPy+g=,tag:/jRa+TqnIdLZyaWJZ1YR0g==,type:str]
kind: Secret
metadata:
    name: aws-s3
    namespace: default
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zefy3yk8qkmr7zvk4fcc09ea9rt0a02kx28yygerx7usu780k9msuy6jth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NXJjR0lJUk9JU3ljL0ZU
            MWNObFpHZHo4RHdMUEk0LzJHZXUydWR1UHo4Cjd4V0tuYmx1VjAxVld3L1ZCbE93
            Qmdha1ZEeXVFMVZ0UnM3WlVtR2U4V3cKLS0tIEphT2FtNmhhZDZQS1Vtbkl4Ukdq
            Q3dtSVFGK3dNOUNWNEVWbkRJMFdsTDAKGQPdFwnm492pZ6NBQ7O2qcVcKjx521pd
            130nqjte9EHvaUeoZG7zfkMjk7o92HDFozf0oOdzE8dLHTkSIQmOFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T11:26:55Z"
    mac: ENC[AES256_GCM,data:IhMqtVzj3VT8ofGytAjMfr38jzbEW0nDOmZwJBTEat3vpkpUHsFEuwY0d7H3WfE9oKDFLF/o9EJS7H1uc79aySPbyyXs57aw/KRnvrhXRgioILcd0KFLemad/ent2/tWn++5xt3dGRcBB6hkz6uCrcftHN2bf6oJldJP7A/4JTg=,iv:N3mvIpvFlDKjMLF9/QCGQy3y15HeHzwd4xZOWntcE2g=,tag:JscPrqP2d9YMsI1g0wr3cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|accessKeyID|password)$
    version: 3.7.3
