apiVersion: v1
data:
    token: ENC[AES256_GCM,data:meaapNcCviURNM2M473Sgb7D2CL/V9tlusdkj0ZpzNZGrGsTDCsqpn08I85X5aiiwmV1383ojXd73ajZMN39Xi0Issr7ERvvK4IlPnlTPA0=,iv:Od1oxuQIwjYrRw7oqjnhjn8ua+tJsKk2eV0Syi17y1Y=,tag:tgD8UFinLIKaTC3uyeQVeg==,type:str]
kind: Secret
metadata:
    name: 52poke-discord
    namespace: default
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zefy3yk8qkmr7zvk4fcc09ea9rt0a02kx28yygerx7usu780k9msuy6jth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQUZyTC9qUmFzTkphMGdk
            NWg2SFo1RzdQRjd2VE5IcUkwazJ0Uk9Rd2djClpSYVVhMnRESXpnaWJZS2t4WG1G
            cm52aGoybTJIblI4UmN2U2tudkZTdWsKLS0tIGhIOXZOY29pUEVYMzhrbG9VSmhX
            RHdOWUtyUmEzZ2NFcWZRK2NFK1V5VFUKbHgnnPSUaK8KKZ/3nF/tZyY/Z9YuH3+P
            LJOaQImhdsGIbt4qh74VB9izwWvaCt2f2K/Ctue+fYze6mBCJ+eeFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T11:23:00Z"
    mac: ENC[AES256_GCM,data:c7BtISRPOTEZX/CkMfKPD0IgH/umDqFdpCQWnVx6wlMuJqiQrKutZ6zEhe2rN613K2hoG5VIx3lbryXntj2Pur4ve1X7dU3Sg7Tph9XbW2oNUCIXGw0vgc/LNabMjs/bRis1RtPyJhar/5y+7w6iwmR/4r35s7yVWSXL9x2iIbE=,iv:d7pEMF5k1T6Zo3dC53xmE9BkBI2ej9/TYz5K6lu6xrk=,tag:bod2gu2G0T1Vag8ghK/JYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|accessKeyID|password)$
    version: 3.7.3
