---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: terraform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - update
  - create
  - list
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform
  namespace: terraform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: terraform
subjects:
- kind: ServiceAccount
  name: terraform
  namespace: default