apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- "job.yaml"
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: terraform-database
  files:
  - "main.tf=main.tf"
  - "mariadb.tf=mariadb.tf"
  - "mariadb-pc.tf=mariadb-pc.tf"
  - "postgres.tf=postgres.tf"
  - "variables.tf=variables.tf"
  - "versions.tf=versions.tf"