apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: default
spec:
  selector:
    matchLabels:
      app: memcached
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - image: memcached
        imagePullPolicy: Always
        name: memcached
        ports:
        - containerPort: 11211
          name: memcached
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      nodeSelector:
        lke.linode.com/pool-id: "125654"
      restartPolicy: Always