apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubepoke-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubepoke
  namespace: default
roleRef:
  kind: Role
  name: kubepoke-role
  apiGroup: rbac.authorization.k8s.io