apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: metrics-server
      version: "3.8.4"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    args:
      - "--kubelet-preferred-address-types=InternalIP"
      - "--kubelet-insecure-tls"
    nodeSelector:
      lke.linode.com/pool-id: "125654"